//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找已本地化的字符串等等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class adminNav {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal adminNav() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.adminNav", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找重写当前线程的 CurrentUICulture 
        /// 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cache Configuration 的本地化字符串。
        /// </summary>
        internal static string CacheConfiguration {
            get {
                return ResourceManager.GetString("CacheConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Community Forums 的本地化字符串。
        /// </summary>
        internal static string CommunityForums {
            get {
                return ResourceManager.GetString("CommunityForums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Configuration 的本地化字符串。
        /// </summary>
        internal static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Configure Cache Providers 的本地化字符串。
        /// </summary>
        internal static string ConfigureCacheProviders {
            get {
                return ResourceManager.GetString("ConfigureCacheProviders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Configure Payment Providers 的本地化字符串。
        /// </summary>
        internal static string ConfigurePaymentProviders {
            get {
                return ResourceManager.GetString("ConfigurePaymentProviders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Configure Shipping Providers 的本地化字符串。
        /// </summary>
        internal static string ConfigureShippingProviders {
            get {
                return ResourceManager.GetString("ConfigureShippingProviders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Configure Tax Providers 的本地化字符串。
        /// </summary>
        internal static string ConfigureTaxProviders {
            get {
                return ResourceManager.GetString("ConfigureTaxProviders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Content Management 的本地化字符串。
        /// </summary>
        internal static string ContentManagement {
            get {
                return ResourceManager.GetString("ContentManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Coupons 的本地化字符串。
        /// </summary>
        internal static string Coupons {
            get {
                return ResourceManager.GetString("Coupons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Customer Information 的本地化字符串。
        /// </summary>
        internal static string CustomerInformation {
            get {
                return ResourceManager.GetString("CustomerInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Customer Service 的本地化字符串。
        /// </summary>
        internal static string CustomerService {
            get {
                return ResourceManager.GetString("CustomerService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 dashCommerce.com 的本地化字符串。
        /// </summary>
        internal static string dashCommercecom {
            get {
                return ResourceManager.GetString("dashCommercecom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 dashCommerce.org 的本地化字符串。
        /// </summary>
        internal static string dashCommerceorg {
            get {
                return ResourceManager.GetString("dashCommerceorg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 dashBoard 的本地化字符串。
        /// </summary>
        internal static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Documentation 的本地化字符串。
        /// </summary>
        internal static string Documentation {
            get {
                return ResourceManager.GetString("Documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error Logs 的本地化字符串。
        /// </summary>
        internal static string ErrorLogs {
            get {
                return ResourceManager.GetString("ErrorLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 General Cache Settings 的本地化字符串。
        /// </summary>
        internal static string GeneralCacheProviderSettings {
            get {
                return ResourceManager.GetString("GeneralCacheProviderSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 General Payment Settings 的本地化字符串。
        /// </summary>
        internal static string GeneralPaymentProviderSettings {
            get {
                return ResourceManager.GetString("GeneralPaymentProviderSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 These are the general settings for the payment service. These settings are not payment provider specific and apply at the store level. 的本地化字符串。
        /// </summary>
        internal static string GeneralPaymentProviderSettingsDescription {
            get {
                return ResourceManager.GetString("GeneralPaymentProviderSettingsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 General Shipping Settings 的本地化字符串。
        /// </summary>
        internal static string GeneralShippingProviderSettings {
            get {
                return ResourceManager.GetString("GeneralShippingProviderSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 General Tax Settings 的本地化字符串。
        /// </summary>
        internal static string GeneralTaxProviderSettings {
            get {
                return ResourceManager.GetString("GeneralTaxProviderSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Help 的本地化字符串。
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mail Configuration 的本地化字符串。
        /// </summary>
        internal static string MailConfiguration {
            get {
                return ResourceManager.GetString("MailConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mail Settings 的本地化字符串。
        /// </summary>
        internal static string MailSettings {
            get {
                return ResourceManager.GetString("MailSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Manage Cache Providers 的本地化字符串。
        /// </summary>
        internal static string ManageCacheProviders {
            get {
                return ResourceManager.GetString("ManageCacheProviders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Manage Coupon Providers 的本地化字符串。
        /// </summary>
        internal static string ManageCouponProviders {
            get {
                return ResourceManager.GetString("ManageCouponProviders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Manage Payment Providers 的本地化字符串。
        /// </summary>
        internal static string ManagePaymentProviders {
            get {
                return ResourceManager.GetString("ManagePaymentProviders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Manage Shipping Providers 的本地化字符串。
        /// </summary>
        internal static string ManageShippingProviders {
            get {
                return ResourceManager.GetString("ManageShippingProviders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Manage Tax Providers 的本地化字符串。
        /// </summary>
        internal static string ManageTaxProviders {
            get {
                return ResourceManager.GetString("ManageTaxProviders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Notifications 的本地化字符串。
        /// </summary>
        internal static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Order Search 的本地化字符串。
        /// </summary>
        internal static string OrderSearch {
            get {
                return ResourceManager.GetString("OrderSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Payment Configuration 的本地化字符串。
        /// </summary>
        internal static string PaymentConfiguration {
            get {
                return ResourceManager.GetString("PaymentConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Payment Solutions 的本地化字符串。
        /// </summary>
        internal static string PaymentSolutions {
            get {
                return ResourceManager.GetString("PaymentSolutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sign Up for Your Preferred Payment Solution! 的本地化字符串。
        /// </summary>
        internal static string PaymentSolutionsDescription {
            get {
                return ResourceManager.GetString("PaymentSolutionsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PayPal Payment Configuration 的本地化字符串。
        /// </summary>
        internal static string PayPalPaymentConfiguration {
            get {
                return ResourceManager.GetString("PayPalPaymentConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Product Attributes 的本地化字符串。
        /// </summary>
        internal static string ProductAttributes {
            get {
                return ResourceManager.GetString("ProductAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Product Bundles 的本地化字符串。
        /// </summary>
        internal static string ProductBundles {
            get {
                return ResourceManager.GetString("ProductBundles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Product Campaigns ? 的本地化字符串。
        /// </summary>
        internal static string ProductCampaigns {
            get {
                return ResourceManager.GetString("ProductCampaigns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Product Categories 的本地化字符串。
        /// </summary>
        internal static string ProductCategories {
            get {
                return ResourceManager.GetString("ProductCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Product Coupons 的本地化字符串。
        /// </summary>
        internal static string ProductCoupons {
            get {
                return ResourceManager.GetString("ProductCoupons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Product Downloads 的本地化字符串。
        /// </summary>
        internal static string ProductDownloads {
            get {
                return ResourceManager.GetString("ProductDownloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Product Listing 的本地化字符串。
        /// </summary>
        internal static string ProductListing {
            get {
                return ResourceManager.GetString("ProductListing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Product Management 的本地化字符串。
        /// </summary>
        internal static string ProductManagement {
            get {
                return ResourceManager.GetString("ProductManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Product Manufacturers 的本地化字符串。
        /// </summary>
        internal static string ProductManufacturers {
            get {
                return ResourceManager.GetString("ProductManufacturers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Product Promotions ? 的本地化字符串。
        /// </summary>
        internal static string ProductPromotions {
            get {
                return ResourceManager.GetString("ProductPromotions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Product Reviews ? 的本地化字符串。
        /// </summary>
        internal static string ProductReviews {
            get {
                return ResourceManager.GetString("ProductReviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Return To Site 的本地化字符串。
        /// </summary>
        internal static string ReturnToSite {
            get {
                return ResourceManager.GetString("ReturnToSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Role Administration 的本地化字符串。
        /// </summary>
        internal static string RoleAdministration {
            get {
                return ResourceManager.GetString("RoleAdministration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sales 的本地化字符串。
        /// </summary>
        internal static string Sales {
            get {
                return ResourceManager.GetString("Sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Security 的本地化字符串。
        /// </summary>
        internal static string Security {
            get {
                return ResourceManager.GetString("Security", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shipping Configuration 的本地化字符串。
        /// </summary>
        internal static string ShippingConfiguration {
            get {
                return ResourceManager.GetString("ShippingConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Site 的本地化字符串。
        /// </summary>
        internal static string Site {
            get {
                return ResourceManager.GetString("Site", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Site Configuration 的本地化字符串。
        /// </summary>
        internal static string SiteConfiguration {
            get {
                return ResourceManager.GetString("SiteConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Site Settings 的本地化字符串。
        /// </summary>
        internal static string SiteSettings {
            get {
                return ResourceManager.GetString("SiteSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Store Settings 的本地化字符串。
        /// </summary>
        internal static string StoreSettings {
            get {
                return ResourceManager.GetString("StoreSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tax Configuration 的本地化字符串。
        /// </summary>
        internal static string TaxConfiguration {
            get {
                return ResourceManager.GetString("TaxConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tracking Logs 的本地化字符串。
        /// </summary>
        internal static string TrackingLogs {
            get {
                return ResourceManager.GetString("TrackingLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User Administration 的本地化字符串。
        /// </summary>
        internal static string UserAdministration {
            get {
                return ResourceManager.GetString("UserAdministration", resourceCulture);
            }
        }
    }
}
